version: "3"

services:
  nginx1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./www/:/var/www/
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
      - db

  nginx2:
    image: nginx:latest
    ports:
      - "8082:80" # Utilisez un autre port pour éviter les conflits
    volumes:
      - ./www/:/var/www/
      - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
      - db

  php1:
    build: .
    container_name: php1
    volumes:
      - ./www:/var/www/
    depends_on:
      - db
    ports:
      - "9001:9000"

  php2:
    build: .
    container_name: php2
    volumes:
      - ./www:/var/www/
    depends_on:
      - db
    ports:
      - "9002:9000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
